# Generated by Django 6.0.5 on 2026-06-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesmet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroepi',
            name='assinatura_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura Digital'),
        ),
        migrations.AddField(
            model_name='registroepi',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
    ]
