# Generated by Django 6.0.5 on 2026-07-20 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0005_alter_colaborador_marca'),
        ('sesmet', '0002_registroepi_assinatura_base64_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoProtecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do EPI (ex: Luva de Raspa)')),
                ('numero_ca', models.CharField(blank=True, max_length=20, verbose_name='Número do CA')),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('validade_ca', models.DateField(blank=True, null=True, verbose_name='Validade do CA')),
                ('dias_durabilidade', models.PositiveIntegerField(default=30, verbose_name='Durabilidade Estimada (dias)')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipamento de Proteção',
                'verbose_name_plural': 'Equipamentos de Proteção (Catálogo)',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='registroepi',
            options={'ordering': ['-data_movimentacao', '-criado_em'], 'verbose_name': 'Movimentação de EPI', 'verbose_name_plural': 'Movimentações de EPIs'},
        ),
        migrations.RemoveField(
            model_name='registroepi',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='registroepi',
            name='motivo_substituicao',
        ),
        migrations.RemoveField(
            model_name='registroepi',
            name='numero_ca',
        ),
        migrations.RemoveField(
            model_name='registroepi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='registroepi',
            name='tipo_epi',
        ),
        migrations.AddField(
            model_name='registroepi',
            name='data_movimentacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Movimentação'),
        ),
        migrations.AddField(
            model_name='registroepi',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('retirada', 'Retirada (Entrega)'), ('devolucao', 'Devolução'), ('descarte', 'Descarte / Perda')], default='retirada', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroepi',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_epi', to='admissional.colaborador'),
        ),
        migrations.AlterField(
            model_name='registroepi',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento Previsto'),
        ),
        migrations.AlterField(
            model_name='registroepi',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroepi',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='sesmet.equipamentoprotecao'),
            preserve_default=False,
        ),
    ]
