# Generated by Django 6.0.5 on 2026-07-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logatividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='marca',
            field=models.CharField(choices=[('trip_premium', 'Trip Premium'), ('log_premium', 'Log Premium'), ('matriz', 'Matriz Grupo PremiumBR')], default='eco_premium', max_length=20),
        ),
    ]
