# Generated by Django 5.2.17 on 2026-09-18 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_arquivoimportado_origemarquivoimportado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aprovacaoregistro',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela decisão'),
        ),
    ]
