# Generated by Django 6.0.5 on 2026-09-19 12:03

from django.db import migrations

def insert_movida_bases(apps, schema_editor):
    Unidade = apps.get_model('core', 'Unidade')
    
    bases = [
        ("MOV-001", "Piracicaba"),
        ("MOV-002", "Sorocaba"),
        ("MOV-003", "Limeira"),
        ("MOV-004", "Indaiatuba"),
        ("MOV-005", "Bauru"),
        ("MOV-006", "Ribeirão Preto"),
        ("MOV-007", "São Carlos"),
        ("MOV-008", "São José do Rio Preto"),
        ("MOV-009", "Sorocaba Dom Aguirre"),
        ("MOV-010", "Praia Grande"),
        ("MOV-011", "Rio Claro"),
        ("MOV-012", "Goiânia RIO VERDE"),
        ("MOV-013", "Londrina")
    ]
    
    for codigo, nome in bases:
        Unidade.objects.update_or_create(
            codigo=codigo,
            defaults={'nome': nome}
        )

def remove_movida_bases(apps, schema_editor):
    Unidade = apps.get_model('core', 'Unidade')
    codigos = [f"MOV-{i:03d}" for i in range(1, 14)]
    Unidade.objects.filter(codigo__in=codigos).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aprovacaoregistro_destinatario'),
    ]

    operations = [
        migrations.RunPython(insert_movida_bases, remove_movida_bases)
    ]
