# Generated by Django 5.2.17 on 2026-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_perfil_entregas_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoimportado',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='arquivoimportado',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações e detalhamento'),
        ),
    ]
