# Generated by Django 6.0.5 on 2026-06-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0002_talento_candidato_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='talento',
            name='ultima_vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talentos_aplicados', to='recrutamento.vaga', verbose_name='Última Vaga Aplicada'),
        ),
    ]
