# Generated by Django 6.0.5 on 2026-06-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0003_talento_ultima_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='arquivo_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Currículo PDF'),
        ),
        migrations.AddField(
            model_name='talento',
            name='arquivo_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Currículo PDF'),
        ),
    ]
