# Generated by Django 6.0.5 on 2026-07-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0004_candidato_arquivo_pdf_talento_arquivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/', verbose_name='Currículo PDF (Nuvem)'),
        ),
        migrations.AddField(
            model_name='talento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/', verbose_name='Currículo PDF (Nuvem)'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='arquivo_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Currículo PDF (Legado DB)'),
        ),
        migrations.AlterField(
            model_name='talento',
            name='arquivo_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Currículo PDF (Legado DB)'),
        ),
    ]
