# Generated by Django 6.0.5 on 2026-07-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0005_candidato_arquivo_talento_arquivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='talento',
            name='cpf',
        ),
        migrations.AddField(
            model_name='candidato',
            name='cpf_cnpj',
            field=models.CharField(default='000.000.000-00', max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tem_filhos_menores_14',
            field=models.BooleanField(default=False, verbose_name='Tem filhos menores de 14 anos?'),
        ),
        migrations.AddField(
            model_name='talento',
            name='cpf_cnpj',
            field=models.CharField(default='000.000.000-00', max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cidade',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='talento',
            name='cidade',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Cidade'),
        ),
    ]
