# Generated by Django 6.0.5 on 2026-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0006_remove_candidato_cpf_remove_talento_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cidade',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cpf_cnpj',
            field=models.CharField(default='000.000.000-00', max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='talento',
            name='cidade',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='talento',
            name='cpf_cnpj',
            field=models.CharField(default='000.000.000-00', max_length=18, verbose_name='CPF/CNPJ'),
        ),
    ]
