# Generated by Django 5.2 on 2026-09-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0007_alter_candidato_cidade_alter_candidato_cpf_cnpj_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga_id_original', models.PositiveBigIntegerField()),
                ('nome_vaga', models.CharField(max_length=200)),
                ('acao', models.CharField(choices=[('edicao', 'Edição'), ('exclusao', 'Exclusão')], max_length=20)),
                ('motivo', models.CharField(choices=[('erro_digitacao', 'Erro de digitação/cadastro'), ('acidente', 'Acidente ou ocorrência'), ('outros', 'Outros')], max_length=30)),
                ('justificativa', models.TextField()),
                ('dados_anteriores', models.JSONField(default=dict)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('candidatos_afetados', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_vagas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='recrutamento.vaga')),
            ],
            options={
                'verbose_name': 'Histórico de vaga',
                'verbose_name_plural': 'Histórico de vagas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
