# Generated by Django 5.2 on 2026-09-19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('admissional', '0016_folha_periodo_recorrencia_freelancer'),
        ('core', '0012_aprovacaoregistro_destinatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True)),
                ('titulo', models.CharField(max_length=200)),
                ('versao', models.PositiveSmallIntegerField(default=1)),
                ('hash_origem', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('importando', 'Importando'), ('revisao', 'Em revisão'), ('pronta', 'Pronta para processar'), ('processada', 'Processada'), ('erro', 'Erro')], db_index=True, default='importando', max_length=20)),
                ('observacoes_importacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folhas_fiscais', to='core.arquivoimportado')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folhas_fiscais_importadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Folha fiscal', 'verbose_name_plural': 'Folhas fiscais', 'ordering': ['-competencia', '-versao', '-pk']},
        ),
        migrations.CreateModel(
            name='BeneficioFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aba_origem', models.CharField(max_length=80)),
                ('linha_origem', models.PositiveIntegerField()),
                ('nome_fonte', models.CharField(max_length=200)),
                ('pix', models.CharField(blank=True, max_length=180)),
                ('base', models.CharField(blank=True, max_length=180)),
                ('contrato', models.CharField(blank=True, max_length=180)),
                ('tipo', models.CharField(choices=[('vale_transporte', 'Vale-transporte'), ('ajuda_custo', 'Ajuda de custo')], default='vale_transporte', max_length=30)),
                ('valor_passagem_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_fonte', models.CharField(choices=[('pago', 'Pago na planilha'), ('pendente', 'Aguardando pagamento'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=20)),
                ('status_conciliacao', models.CharField(choices=[('conciliado', 'Conciliado'), ('revisar', 'Revisar')], default='revisar', max_length=20)),
                ('problemas', models.JSONField(blank=True, default=list)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_fiscais', to='admissional.colaborador')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='fiscal.folhafiscal')),
            ],
            options={'ordering': ['linha_origem']},
        ),
        migrations.CreateModel(
            name='ItemFolhaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aba_origem', models.CharField(max_length=80)),
                ('linha_origem', models.PositiveIntegerField()),
                ('regime', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('freelancer', 'Freelancer fixo'), ('supervisor', 'Supervisor'), ('administrativo', 'Administrativo'), ('rescisao', 'Rescisão')], db_index=True, max_length=20)),
                ('nome_fonte', models.CharField(max_length=200)),
                ('cpf_cnpj_fonte', models.CharField(blank=True, max_length=30)),
                ('pix', models.CharField(blank=True, max_length=180)),
                ('banco', models.CharField(blank=True, max_length=180)),
                ('cargo', models.CharField(blank=True, max_length=180)),
                ('contrato', models.CharField(blank=True, max_length=180)),
                ('unidade', models.CharField(blank=True, max_length=180)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dias_trabalhados', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bonificacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('faltas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_executar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_planejado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_pagamento_fonte', models.DateField(blank=True, null=True)),
                ('status_fonte', models.CharField(choices=[('pago', 'Pago na planilha'), ('pendente', 'Aguardando pagamento'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=20)),
                ('status_conciliacao', models.CharField(choices=[('conciliado', 'Conciliado'), ('revisar', 'Revisar')], default='revisar', max_length=20)),
                ('problemas', models.JSONField(blank=True, default=list)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_fiscais', to='admissional.colaborador')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.folhafiscal')),
                ('pagamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_fiscal', to='admissional.pagamentocolaborador')),
            ],
            options={'verbose_name': 'Item da folha fiscal', 'verbose_name_plural': 'Itens da folha fiscal', 'ordering': ['aba_origem', 'linha_origem']},
        ),
        migrations.CreateModel(
            name='ParcelaBeneficioFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='fiscal.beneficiofiscal')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_beneficio', to='fiscal.folhafiscal')),
                ('pagamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcela_fiscal', to='admissional.pagamentocolaborador')),
            ],
            options={'ordering': ['beneficio__linha_origem', 'semana']},
        ),
        migrations.AddConstraint(model_name='folhafiscal', constraint=models.UniqueConstraint(fields=('competencia', 'versao'), name='fiscal_folha_competencia_versao_unica')),
        migrations.AddConstraint(model_name='beneficiofiscal', constraint=models.UniqueConstraint(fields=('folha', 'aba_origem', 'linha_origem'), name='fiscal_beneficio_origem_unica')),
        migrations.AddIndex(model_name='itemfolhafiscal', index=models.Index(fields=['folha', 'status_conciliacao'], name='fiscal_item_folha_i_991e02_idx')),
        migrations.AddIndex(model_name='itemfolhafiscal', index=models.Index(fields=['regime', 'status_fonte'], name='fiscal_item_regime_af6782_idx')),
        migrations.AddConstraint(model_name='itemfolhafiscal', constraint=models.UniqueConstraint(fields=('folha', 'aba_origem', 'linha_origem'), name='fiscal_item_origem_unica')),
        migrations.AddConstraint(model_name='parcelabeneficiofiscal', constraint=models.UniqueConstraint(fields=('beneficio', 'semana'), name='fiscal_beneficio_semana_unica')),
        migrations.AddConstraint(model_name='parcelabeneficiofiscal', constraint=models.CheckConstraint(condition=models.Q(('semana__gte', 1), ('semana__lte', 4)), name='fiscal_semana_entre_1_e_4')),
    ]
