# Generated by Django 6.0.5 on 2026-07-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofinanceiro',
            name='arquivo_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Nota Fiscal PDF'),
        ),
        migrations.CreateModel(
            name='OrcamentoCentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custo', models.CharField(max_length=100, verbose_name='Centro de Custo')),
                ('competencia', models.DateField(verbose_name='Mês/Ano (Competência)')),
                ('valor_orcado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Orçado (Budget)')),
                ('meta_reducao_custo', models.DecimalField(decimal_places=2, default=0, help_text='Ex: 5 para 5% de redução', max_digits=5, verbose_name='Meta de Redução (%)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orçamento por Centro de Custo',
                'verbose_name_plural': 'Orçamentos por Centro de Custo',
                'ordering': ['-competencia'],
                'unique_together': {('centro_custo', 'competencia')},
            },
        ),
    ]
