# Generated by Django 6.0.5 on 2026-07-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_documentofinanceiro_arquivo_pdf_orcamentocentrocusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofinanceiro',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='Nota Fiscal PDF (Nuvem)'),
        ),
        migrations.AlterField(
            model_name='documentofinanceiro',
            name='arquivo_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Nota Fiscal PDF (Legado DB)'),
        ),
    ]
