# Generated by Django 6.0.5 on 2026-07-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_documentofinanceiro_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofinanceiro',
            name='cnpj_emitente',
            field=models.CharField(max_length=18, verbose_name='CNPJ do Emitente'),
        ),
        migrations.AlterField(
            model_name='documentofinanceiro',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='documentofinanceiro',
            name='razao_social_emitente',
            field=models.CharField(max_length=200, verbose_name='Razão Social'),
        ),
    ]
