# Generated by Django 6.0.5 on 2026-07-21 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_documentofinanceiro_cnpj_emitente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDocumentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_produto', models.CharField(max_length=255, verbose_name='Descrição do Produto/Serviço')),
                ('ncm', models.CharField(blank=True, max_length=20, verbose_name='NCM')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Total (R$)')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.documentofinanceiro', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Item do Documento',
                'verbose_name_plural': 'Itens do Documento',
            },
        ),
    ]
