# Generated by Django 5.2.17 on 2026-09-26 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_documento_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofinanceiro',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofinanceiro',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_financeiros_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentofinanceiro',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, verbose_name='Motivo do cancelamento'),
        ),
        migrations.AlterField(
            model_name='documentofinanceiro',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('em_auditoria', 'Em Auditoria Interna'), ('informacoes_incorretas', 'Informações Incorretas'), ('aguardando_correcao', 'Aguardando Correção'), ('aprovado_lancamento', 'Aprovado para Lançamento'), ('lancado', 'Lançado no ERP'), ('arquivado', 'Arquivado'), ('cancelado', 'Cancelado')], default='recebido', max_length=30),
        ),
        migrations.AlterField(
            model_name='lancamentoerp',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_validacao', 'Em Validação'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado — Corrigir'), ('finalizado', 'Finalizado no ERP'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20),
        ),
    ]
