# Generated by Django 5.2.17 on 2026-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_documento_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofinanceiro',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações e detalhamento'),
        ),
        migrations.AlterField(
            model_name='documentofinanceiro',
            name='situacao_pagamento',
            field=models.CharField(choices=[('nao_informado', 'Não informado'), ('a_pagar', 'A pagar'), ('pago', 'Pago'), ('a_receber', 'A receber'), ('recebido', 'Recebido')], default='nao_informado', max_length=15, verbose_name='Situação do pagamento'),
        ),
    ]
