# Generated by Django 6.0.5 on 2026-06-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadmissional',
            name='arquivo',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Arquivo do Documento'),
        ),
        migrations.AddField(
            model_name='documentoadmissional',
            name='arquivo_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentoadmissional',
            name='arquivo_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo'),
        ),
    ]
