# Generated by Django 6.0.5 on 2026-07-01 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0002_documentoadmissional_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadmissional',
            name='arquivo_nuvem',
            field=models.FileField(blank=True, null=True, upload_to='documentos_admissional/', verbose_name='Arquivo do Documento (Nuvem)'),
        ),
        migrations.AddField(
            model_name='documentoadmissional',
            name='enviado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentoadmissional',
            name='arquivo',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Arquivo do Documento (Legado DB)'),
        ),
    ]
