# Generated by Django 6.0.5 on 2026-07-08 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0003_documentoadmissional_arquivo_nuvem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início na Empresa'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='tem_filhos_menores_14',
            field=models.BooleanField(default=False, verbose_name='Tem filhos menores de 14 anos?'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_cpf',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_ctps',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CTPS'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_pis',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo PIS/PASEP'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_reservista',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Reservista'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_rg',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo RG'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_titulo',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Título de Eleitor'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='marca',
            field=models.CharField(choices=[('trip_premium', 'Trip Premium'), ('log_premium', 'Log Premium')], default='eco_premium', max_length=20, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='documentoadmissional',
            name='tipo',
            field=models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('ctps', 'Carteira de Trabalho (CTPS)'), ('pis', 'PIS/PASEP'), ('comprovante_residencia', 'Comprovante de Residência'), ('certidao_nascimento', 'Certidão de Nascimento'), ('certidao_casamento', 'Certidão de Casamento'), ('diploma', 'Diploma/Certificado Escolar'), ('foto_3x4', 'Foto 3x4'), ('atestado_saude', 'Atestado de Saúde Ocupacional (ASO)'), ('dados_bancarios', 'Dados Bancários'), ('antecedentes', 'Certidão de Antecedentes Criminais'), ('titulo_eleitor', 'Título de Eleitor'), ('reservista', 'Certificado de Reservista'), ('carteira_vacinacao', 'Carteira de Vacinação dos Filhos')], max_length=30),
        ),
        migrations.CreateModel(
            name='PresencaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta'), ('atestado', 'Atestado/Licença'), ('folga', 'Folga')], default='presente', max_length=20)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='admissional.colaborador')),
            ],
            options={
                'verbose_name': 'Presença Diária',
                'verbose_name_plural': 'Controle de Presenças',
                'ordering': ['-data', 'colaborador__nome'],
                'unique_together': {('colaborador', 'data')},
            },
        ),
    ]
