# Generated by Django 6.0.5 on 2026-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0004_admissao_data_inicio_admissao_tem_filhos_menores_14_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='marca',
            field=models.CharField(choices=[('trip_premium', 'Trip Premium'), ('log_premium', 'Log Premium'), ('eco_premium', 'Eco Premium')], default='eco_premium', max_length=20, verbose_name='Marca'),
        ),
    ]
