# Generated by Django 6.0.5 on 2026-08-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0005_alter_colaborador_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='anexo_cpf_verso',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CPF/CNPJ (Verso)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_ctps_verso',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CTPS (Verso)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_pis_verso',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo PIS/PASEP (Verso)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_reservista_verso',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Reservista (Verso)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_rg_verso',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo RG (Verso)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='anexo_titulo_verso',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Título de Eleitor (Verso)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ')], default='clt', max_length=10, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_cpf',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CPF/CNPJ (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_ctps',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CTPS (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_pis',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo PIS/PASEP (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_reservista',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Reservista (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_rg',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo RG (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_titulo',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Título de Eleitor (Frente)'),
        ),
    ]
