# Generated by Django 6.0.5 on 2026-08-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0006_colaborador_anexo_cpf_verso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='anexo_aso',
            field=models.FileField(blank=True, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo ASO (Atestado de Saúde Ocupacional)'),
        ),
    ]
