# Generated by Django 6.0.5 on 2026-08-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0007_colaborador_anexo_aso'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='contrato',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contrato/Cliente'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
    ]
