# Generated by Django 5.2.17 on 2026-09-12 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0008_add_contrato_field_and_blank_email_telefone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comprovante_endereco', 'Comprovante de endereço'), ('ajuda_custo', 'Ajuda de custo semanal'), ('comprovante_servico', 'Comprovante de serviço'), ('contrato', 'Contrato')], max_length=30)),
                ('arquivo', models.FileField(upload_to='colaboradores/documentos/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='Data de referência')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_arquivo', to='admissional.colaborador')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_colaboradores_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento do colaborador',
                'verbose_name_plural': 'Documentos dos colaboradores',
                'ordering': ['-data_referencia', '-criado_em'],
                'indexes': [models.Index(fields=['colaborador', 'tipo', 'data_referencia'], name='admissional_colabor_5bf2f8_idx')],
            },
        ),
    ]
