# Generated by Django 6.0.5 on 2026-09-16 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0012_pagamentocolaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ajuda_custo_semanal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ajuda de custo semanal'),
        ),
        migrations.AlterField(
            model_name='pagamentocolaborador',
            name='tipo',
            field=models.CharField(choices=[('salario', 'Salário'), ('vale_transporte', 'Vale-transporte'), ('ajuda_custo', 'Ajuda de custo')], max_length=30),
        ),
    ]
