# Generated by Django 5.2.17 on 2026-09-26 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0025_salario_unico_por_competencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacaoVT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda', models.DateField(db_index=True)),
                ('pagar', models.BooleanField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissional.colaborador')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('colaborador', 'segunda'), name='vt_decisao_por_semana')],
            },
        ),
    ]
