# Generated by Django 5.2.17 on 2026-09-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0026_programacao_vt_semanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacaovt',
            name='dias_presentes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacaovt',
            name='valor_semana_completa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
