# Generated by Django 5.2.17 on 2026-09-30 11:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0027_calculo_proporcional_vt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocolaborador',
            name='faltas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Faltas a descontar (dias)'),
        ),
        migrations.AddField(
            model_name='pagamentocolaborador',
            name='gratificacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gratificação integral'),
        ),
        migrations.AddField(
            model_name='pagamentocolaborador',
            name='outros_descontos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Outros descontos / adiantamentos'),
        ),
        migrations.AddField(
            model_name='pagamentocolaborador',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salário mensal para cálculo'),
        ),
        migrations.AddField(
            model_name='programacaovt',
            name='antecipado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programacaovt',
            name='desconto_adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='programacaovt',
            name='diaria_desconto',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='programacaovt',
            name='dias_jornada',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacaovt',
            name='dias_previstos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacaovt',
            name='faltas_descontar',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
