# Generated by Django 5.2.17 on 2026-09-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0027_calculo_proporcional_vt'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave PIX'),
        ),
    ]
