# Generated by Django 5.2.17 on 2026-09-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissional', '0029_colaborador_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_aso',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo ASO (Atestado de Saúde Ocupacional)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_cpf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CPF/CNPJ (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_cpf_verso',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CPF/CNPJ (Verso)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_ctps',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CTPS (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_ctps_verso',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo CTPS (Verso)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_pis',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo PIS/PASEP (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_pis_verso',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo PIS/PASEP (Verso)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_reservista',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Reservista (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_reservista_verso',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Reservista (Verso)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_rg',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo RG (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_rg_verso',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo RG (Verso)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_titulo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Título de Eleitor (Frente)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='anexo_titulo_verso',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='colaboradores/docs/', verbose_name='Anexo Título de Eleitor (Verso)'),
        ),
    ]
