# Generated by Django 5.2.17 on 2026-09-16 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_material_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('unidade_destino', models.CharField(max_length=100, verbose_name='Unidade de Destino')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitante_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisição de Compra',
                'verbose_name_plural': 'Requisições de Compra',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='solicitacaomaterial',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.requisicaocompra', verbose_name='Requisição agrupada'),
        ),
    ]
