# Generated by Django 5.2.17 on 2026-09-18 19:21

from django.conf import settings
from django.db import migrations, models


def sincronizar_solicitacoes(apps, schema_editor):
    PedidoCompra = apps.get_model('compras', 'PedidoCompra')
    SolicitacaoMaterial = apps.get_model('compras', 'SolicitacaoMaterial')
    aguardando_entrega = PedidoCompra.objects.filter(
        status__in=('pedido_emitido', 'aguardando_recebimento', 'recebido_conferencia')
    ).values('solicitacao_id')
    entregues = PedidoCompra.objects.filter(
        status__in=('entrada_estoque', 'concluido')
    ).values('solicitacao_id')
    SolicitacaoMaterial.objects.filter(id__in=aguardando_entrega).update(
        status='aguardando_entrega'
    )
    SolicitacaoMaterial.objects.filter(id__in=entregues).update(status='entregue')


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_requisicaocompra_solicitacaomaterial_requisicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedidocompra',
            name='compras_valor_unitario_nao_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='pedidocompra',
            name='compras_valor_total_nao_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='solicitacaomaterial',
            name='compras_quantidade_solicitada_nao_negativa',
        ),
        migrations.RunPython(sincronizar_solicitacoes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='pedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gt', 0)), name='compras_valor_unitario_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='compras_valor_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pedidocompra',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reprovado'), _negated=True), fields=('solicitacao',), name='compras_um_pedido_ativo_por_solicitacao'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaomaterial',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_solicitada__gt', 0)), name='compras_quantidade_solicitada_positiva'),
        ),
    ]
