# Generated by Django 5.2.17 on 2026-09-18 19:41

from django.db import migrations, models


def marcar_requisicoes_anteriores_como_aprovadas(apps, schema_editor):
    RequisicaoCompra = apps.get_model('compras', 'RequisicaoCompra')
    RequisicaoCompra.objects.update(status='aprovada')


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_remove_pedidocompra_compras_valor_unitario_nao_negativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaocompra',
            name='status',
            field=models.CharField(choices=[('aguardando_adriana', 'Aguardando aprovação da Adriana'), ('aguardando_ceo', 'Aguardando aprovação do CEO'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='aguardando_adriana', max_length=30),
        ),
        migrations.RunPython(
            marcar_requisicoes_anteriores_como_aprovadas,
            migrations.RunPython.noop,
        ),
    ]
