# Generated by Django 6.0.5 on 2026-09-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_requisicaocompra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaocompra',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='compras/requisicoes/documentos/', verbose_name='Documento Anexo'),
        ),
    ]
