# Generated by Django 6.0.5 on 2026-09-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_requisicaocompra_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaocompra',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='compras/requisicoes/comprovantes/', verbose_name='Comprovante de Pagamento'),
        ),
    ]
