# Generated by Django 6.0.5 on 2026-09-19 12:11

from django.db import migrations
from decimal import Decimal

def insert_products(apps, schema_editor):
    Material = apps.get_model('compras', 'Material')
    
    products = [
        ("PERFUME AROMATIZANTE 5 L", "65.00"),
        ("SILICONE LÍQUIDO PERFUMADO 5 L", "170.00"),
        ("SHAMPOO CONCENTRADO 20 L", "110.00"),
        ("SHAMPOO CONCENTRADO 50 L", "205.00"),
        ("MULTI USO APC 20 L", "110.00"),
        ("MULTI USO APC 50 L", "215.00"),
        ("MULTI USO PERFUMADO CONC. 20 L", "240.00"),
        ("MULTI USO PERFUMADO CONC. 50 L", "395.00"),
        ("DESINCRUSTANTE CONCENTRADO (ROXO) 20 L", "110.00"),
        ("DESINCRUSTANTE CONCENTRADO (ROXO) 50 L", "205.00"),
        ("DESINCRUSTANTE 1X100 (ROXO) 50 L", "395.00"),
        ("DESENGRAXANTE CONCENTRADO (ROSA) 20 L", "110.00"),
        ("DESENGRAXANTE CONCENTRADO (ROSA) 50 L", "205.00"),
        ("DESENGRAXANTE 1X100 (AZUL) 50 L", "395.00"),
        ("LIMPA PNEU (PRETINHO) AZUL GEL 20 L", "140.00"),
        ("LIMPA PNEU (PRETINHO) AZUL GEL 50 L", "245.00"),
        ("ECO DIESEL CONCENTRADO 20 L", "240.00"),
        ("ECO DIESEL CONCENTRADO 50 L", "430.00"),
        ("TIRA COLA 20 L", "990.00"),
        ("CERA LÍQUIDA BRANCA 20 L", "110.00"),
        ("CERA LÍQUIDA BRANCA 50 L", "205.00")
    ]
    
    for nome, preco in products:
        mat, created = Material.objects.get_or_create(
            nome=nome,
            defaults={
                'categoria': 'limpeza',
                'unidade_medida': 'un',
                'preco_unitario': Decimal(preco),
                'fornecedor_preferencial': 'E.S Produtos Car Care'
            }
        )
        if created:
            mat.codigo = f"MAT-{mat.pk:06d}"
            mat.save()

def remove_products(apps, schema_editor):
    Material = apps.get_model('compras', 'Material')
    Material.objects.filter(fornecedor_preferencial='E.S Produtos Car Care').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_requisicaocompra_comprovante_pagamento'),
    ]

    operations = [
        migrations.RunPython(insert_products, remove_products)
    ]
