# Generated by Django 5.2.17 on 2026-09-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_insert_es_car_care_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomaterial',
            name='valor_unitario_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário Informado'),
        ),
    ]
