# Generated by Django 5.2.17 on 2026-09-28 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_solicitacaomaterial_valor_unitario_estimado'),
        ('core', '0015_arquivoimportado_processamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisaoItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('aprovado', 'Aprovado'), ('rejeitado', 'Desaprovado')], max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('decidido_em', models.DateTimeField(auto_now=True)),
                ('aprovacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_itens_requisicao', to='core.aprovacaoregistro')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_aprovacao', to='compras.solicitacaomaterial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aprovacao', 'item'), name='compras_decisao_unica_por_etapa_item')],
            },
        ),
    ]
