# Generated by Django 5.2.17 on 2026-10-03 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def proteger_itens_no_postgres(apps, schema_editor):
    # O ERP usa o backend Django; os itens não devem ser expostos pela Data API.
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE compras_itempedidocompra ENABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_manutencao_sem_aprovacao_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='compras.requisicaocompra', verbose_name='Requisição de Origem'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='compras.solicitacaomaterial', verbose_name='Solicitação de Origem'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário'),
        ),
        migrations.AddConstraint(
            model_name='pedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requisicao__isnull', True), ('solicitacao__isnull', False), ('valor_unitario__isnull', False)), models.Q(('requisicao__isnull', False), ('solicitacao__isnull', True), ('valor_unitario__isnull', True)), _connector='OR'), name='compras_pedido_origem_valida'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='compras.solicitacaomaterial'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.UniqueConstraint(fields=('pedido', 'solicitacao'), name='compras_item_unico_no_pedido'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('solicitacao',), name='compras_um_item_pedido_ativo'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='compras_item_pedido_qtd_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gt', 0)), name='compras_item_pedido_preco_positivo'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='compras_item_pedido_total_positivo'),
        ),
        migrations.RunPython(proteger_itens_no_postgres, migrations.RunPython.noop),
    ]
