# Generated by Django 6.0.5 on 2026-07-31 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(max_length=50, unique=True, verbose_name='Número de Patrimônio')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Equipamento/Ativo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Especificações')),
                ('unidade_atual', models.CharField(max_length=100, verbose_name='Unidade Atual')),
                ('status', models.CharField(choices=[('ativo', 'Ativo / Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Baixado / Inativo')], default='ativo', max_length=20, verbose_name='Status')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Aquisição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ativo (Patrimônio)',
                'verbose_name_plural': 'Ativos (Patrimônio)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_origem', models.CharField(max_length=100, verbose_name='Unidade de Origem (Onde estava)')),
                ('motivo', models.TextField(verbose_name='Motivo da Manutenção / Defeito')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('aberta', 'Aberta / Em Análise'), ('andamento', 'Em Andamento (Conserto)'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status da Manutenção')),
                ('custo_reparo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo do Reparo (R$)')),
                ('fornecedor_servico', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor / Técnico')),
                ('obs', models.TextField(blank=True, verbose_name='Observações / Laudo Técnico')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='manutencao.ativo', verbose_name='Equipamento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Manutenção',
                'verbose_name_plural': 'Registros de Manutenção',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
