# Generated by Django 6.0.5 on 2026-08-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromanutencao',
            name='foto_equipamento',
            field=models.ImageField(blank=True, null=True, upload_to='manutencao/', verbose_name='Foto do Equipamento'),
        ),
        migrations.AlterField(
            model_name='registromanutencao',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando Aprovação (CEO)'), ('aberta', 'Aberta / Em Análise'), ('andamento', 'Em Andamento (Conserto)'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status da Manutenção'),
        ),
    ]
