# Generated by Django 6.0.5 on 2026-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_registromanutencao_foto_equipamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipamentos/', verbose_name='Foto do Equipamento'),
        ),
    ]
