# Generated by Django 6.0.5 on 2026-08-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_ativo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Série'),
        ),
    ]
